const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://katanemo.com";

export const siteConfig = {
  name: "Katanemo",
  tagline: "Forward-deployed AI infrastructure engineers",
  description:
    "Forward-deployed AI infrastructure engineers delivering industry-leading research and open-source technologies for agentic AI development efforts.",
  url: BASE_URL,
  ogImage: `${BASE_URL}/KatanemoLogo.svg`,
  links: {
    docs: "https://docs.katanemo.com",
    github: "https://github.com/katanemo/plano",
    discord: "https://discord.gg/pGZf2gcwEc",
    huggingface: "https://huggingface.co/katanemo",
  },
  keywords: [
    "Katanemo AI",
    "Katanemo",
    "Katanemo Labs",
    "forward-deployed AI engineers",
    "forward deployed AI infrastructure",
    "AI infrastructure engineers",
    "embedded AI engineers",
    "on-site AI engineers",
    "model training",
    "AI model research",
    "LLM model training",
    "machine learning model development",
    "custom AI model training",
    "open source agentic AI",
    "agentic AI stack",
    "AI agent infrastructure",
    "open source agent framework",
    "agentic AI development",
    "AI agent platform",
    "Plano agent infrastructure",
    "LLM infrastructure",
    "AI infrastructure platform",
    "agentic AI tools",
    "AI agent orchestration",
    "open source AI stack",
    "enterprise AI infrastructure",
    "production AI systems",
    "AI deployment infrastructure",
  ],
  authors: [{ name: "Katanemo", url: "https://github.com/katanemo/plano" }],
  creator: "Katanemo",
};
